using DocDown.Core;

namespace DemaConsulting.DocDown.Core.Tests.Output;

/// <summary>
///     Unit tests for <see cref="ImageTextSelector"/>, the shared policy that ranks image text and
///     reports how confidently it describes a picture.
/// </summary>
/// <remarks>
///     These tests bind only to <see cref="ImageTextSelector"/> and its value types. They prove the
///     ranking honors source order, that empty and auto-generated names are ignored, that the
///     confidence tier matches the winning source, and that the fallback path never invents a
///     description — the honesty properties every format backend depends on.
/// </remarks>
public class ImageTextSelectorTests
{
    /// <summary>
    ///     Proves a description outranks every weaker source when several are present.
    /// </summary>
    [Fact]
    public void ImageTextSelector_Select_DescriptionPresent_OutranksWeakerSources()
    {
        // Arrange: candidates offered out of preference order, all populated
        var candidates = new[]
        {
            new ImageTextCandidate("nearest-heading", ImageTextSource.Heading),
            new ImageTextCandidate("media1.png", ImageTextSource.Uri),
            new ImageTextCandidate("A wiring diagram", ImageTextSource.Description),
            new ImageTextCandidate("Figure 1", ImageTextSource.Caption)
        };

        // Act: rank them
        var selected = ImageTextSelector.Select(candidates);

        // Assert: the authored description wins and is marked descriptive
        Assert.NotNull(selected);
        Assert.Equal("A wiring diagram", selected.Text);
        Assert.Equal(ImageTextSource.Description, selected.Source);
        Assert.Equal(ImageTextConfidence.Descriptive, selected.Confidence);
    }

    /// <summary>
    ///     Proves a nearby heading is chosen only as a last resort before the media name and is
    ///     marked contextual, not descriptive.
    /// </summary>
    [Fact]
    public void ImageTextSelector_Select_OnlyHeadingAndUri_ChoosesHeadingAsContextual()
    {
        // Arrange: nothing descriptive, only a heading and the media name
        var candidates = new[]
        {
            new ImageTextCandidate(null, ImageTextSource.Description),
            new ImageTextCandidate("  ", ImageTextSource.Title),
            new ImageTextCandidate("References", ImageTextSource.Heading),
            new ImageTextCandidate("image1.png", ImageTextSource.Uri)
        };

        // Act: rank them
        var selected = ImageTextSelector.Select(candidates);

        // Assert: the heading wins over the media name but is only contextual
        Assert.NotNull(selected);
        Assert.Equal("References", selected.Text);
        Assert.Equal(ImageTextSource.Heading, selected.Source);
        Assert.Equal(ImageTextConfidence.Contextual, selected.Confidence);
    }

    /// <summary>
    ///     Proves the media name is the fallback of last resort and is marked as such.
    /// </summary>
    [Fact]
    public void ImageTextSelector_Select_OnlyUri_ChoosesUriAsFallback()
    {
        // Arrange: only the media name carries anything
        var candidates = new[]
        {
            new ImageTextCandidate(null, ImageTextSource.Description),
            new ImageTextCandidate("image7.png", ImageTextSource.Uri)
        };

        // Act: rank them
        var selected = ImageTextSelector.Select(candidates);

        // Assert: the media name is chosen but only as a bare fallback
        Assert.NotNull(selected);
        Assert.Equal("image7.png", selected.Text);
        Assert.Equal(ImageTextConfidence.Fallback, selected.Confidence);
    }

    /// <summary>
    ///     Proves an auto-generated object name is discarded so a weaker but honest source wins.
    /// </summary>
    [Fact]
    public void ImageTextSelector_Select_AutoGeneratedPictureName_FallsThroughToNextSource()
    {
        // Arrange: the object name is a placeholder; a heading is the next-best honest source
        var candidates = new[]
        {
            new ImageTextCandidate("Picture 1", ImageTextSource.PictureName),
            new ImageTextCandidate("Overview", ImageTextSource.Heading)
        };

        // Act: rank them
        var selected = ImageTextSelector.Select(candidates);

        // Assert: the placeholder never wins; the heading is chosen instead
        Assert.NotNull(selected);
        Assert.Equal("Overview", selected.Text);
        Assert.Equal(ImageTextSource.Heading, selected.Source);
    }

    /// <summary>
    ///     Proves a meaningful object name is kept and treated as descriptive.
    /// </summary>
    [Fact]
    public void ImageTextSelector_Select_MeaningfulPictureName_IsDescriptive()
    {
        // Arrange: a real object name that is not a generic placeholder
        var candidates = new[]
        {
            new ImageTextCandidate("blueprint-level-2", ImageTextSource.PictureName),
            new ImageTextCandidate("Building", ImageTextSource.Heading)
        };

        // Act: rank them
        var selected = ImageTextSelector.Select(candidates);

        // Assert: the object name wins and is descriptive
        Assert.NotNull(selected);
        Assert.Equal("blueprint-level-2", selected.Text);
        Assert.Equal(ImageTextSource.PictureName, selected.Source);
        Assert.Equal(ImageTextConfidence.Descriptive, selected.Confidence);
    }

    /// <summary>
    ///     Proves the chosen text is trimmed of surrounding whitespace.
    /// </summary>
    [Fact]
    public void ImageTextSelector_Select_PaddedText_IsTrimmed()
    {
        // Arrange: the winning candidate has surrounding whitespace
        var candidates = new[] { new ImageTextCandidate("  A diagram  ", ImageTextSource.Description) };

        // Act: rank them
        var selected = ImageTextSelector.Select(candidates);

        // Assert: the surrounding whitespace is removed
        Assert.NotNull(selected);
        Assert.Equal("A diagram", selected.Text);
    }

    /// <summary>
    ///     Proves that when no candidate carries usable text the result is null, never a guess.
    /// </summary>
    [Fact]
    public void ImageTextSelector_Select_NoUsableText_ReturnsNull()
    {
        // Arrange: every candidate is empty
        var candidates = new[]
        {
            new ImageTextCandidate(null, ImageTextSource.Description),
            new ImageTextCandidate("   ", ImageTextSource.Caption),
            new ImageTextCandidate(null, ImageTextSource.Uri)
        };

        // Act: rank them
        var selected = ImageTextSelector.Select(candidates);

        // Assert: nothing is chosen
        Assert.Null(selected);
    }

    /// <summary>
    ///     Proves a null candidate set is rejected rather than silently treated as empty.
    /// </summary>
    [Fact]
    public void ImageTextSelector_Select_NullCandidates_Throws() =>
        Assert.Throws<ArgumentNullException>(() => ImageTextSelector.Select(null!));

    /// <summary>
    ///     Proves the auto-generated filter matches generic names with and without a trailing number.
    /// </summary>
    /// <param name="name">The candidate object name.</param>
    [Theory]
    [InlineData("")]
    [InlineData("   ")]
    [InlineData("Picture 1")]
    [InlineData("Image 80")]
    [InlineData("picture")]
    [InlineData("Diagram")]
    [InlineData("Content Placeholder 3")]
    public void ImageTextSelector_IsAutoGeneratedName_GenericNames_ReturnTrue(string name) =>
        Assert.True(ImageTextSelector.IsAutoGeneratedName(name));

    /// <summary>
    ///     Proves the auto-generated filter keeps meaningful names, including those ending in a number.
    /// </summary>
    /// <param name="name">The candidate object name.</param>
    [Theory]
    [InlineData("logo")]
    [InlineData("blueprint-level-2")]
    [InlineData("Site Map 2024")]
    public void ImageTextSelector_IsAutoGeneratedName_MeaningfulNames_ReturnFalse(string name) =>
        Assert.False(ImageTextSelector.IsAutoGeneratedName(name));

    /// <summary>
    ///     Proves every source projects to a distinct, camelCase provenance name.
    /// </summary>
    [Fact]
    public void ImageTextSelector_SourceName_EverySource_ProjectsDistinctCamelCase()
    {
        // Arrange: every declared source
        var sources = Enum.GetValues<ImageTextSource>();

        // Act: project each to its provenance name
        var names = sources.Select(ImageTextSelector.SourceName).ToList();

        // Assert: every name is non-empty, camelCase, and distinct
        Assert.All(names, name =>
        {
            Assert.False(string.IsNullOrWhiteSpace(name));
            Assert.True(char.IsLower(name[0]), $"'{name}' is not camelCase.");
        });
        Assert.Equal(sources.Length, names.Distinct(StringComparer.Ordinal).Count());
    }
}
