using System.Text;

namespace DocDown.Core;

/// <summary>
///     Chooses the best available text to describe an image from a set of candidates, and reports
///     how confidently that text describes the picture.
/// </summary>
/// <remarks>
///     <para>
///         This is the one place the policy for image naming and alt text lives, so every format
///         backend behaves the same way. A backend gathers whatever a document offers about an image
///         — an authored description, a title, a caption, an embedded object name, a nearby heading,
///         the media part name — tags each with its <see cref="ImageTextSource"/>, and hands the set
///         here. The policy keeps the most directly descriptive candidate, discarding empty text and
///         obviously auto-generated object names such as <c>Picture 1</c>.
///     </para>
///     <para>
///         The result carries a confidence tier so callers can be honest about how they use it: a
///         filename slug may use any non-empty selection, but alt text is asserted only for a
///         <see cref="ImageTextConfidence.Descriptive"/> selection, never for a heading or a bare
///         media name. Refusing to promote a heading to alt text is deliberate — presenting a
///         section heading as a picture's description would imply information the document never
///         provided. Pure, stateless, and thread-safe.
///     </para>
/// </remarks>
public static class ImageTextSelector
{
    /// <summary>
    ///     The lowercased base names object properties carry when a tool auto-named a shape.
    /// </summary>
    /// <remarks>
    ///     These are the default names Office assigns when an author never named a drawing; treating
    ///     them as descriptions would be misleading, so a candidate object name that reduces to one
    ///     of these (with an optional trailing number) is discarded rather than used.
    /// </remarks>
    private static readonly HashSet<string> AutoGeneratedNames = new(StringComparer.Ordinal)
    {
        "picture", "image", "graphic", "chart", "object", "diagram", "drawing", "shape",
        "group", "freeform", "rectangle", "oval", "content placeholder", "text box", "placeholder"
    };

    /// <summary>
    ///     Selects the best-ranked descriptive text from a set of candidates.
    /// </summary>
    /// <param name="candidates">The candidates to rank. Must not be null; individual entries may carry null text.</param>
    /// <returns>
    ///     The chosen text with its source and confidence, or <see langword="null"/> when no
    ///     candidate offers usable text.
    /// </returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="candidates"/> is <see langword="null"/>.</exception>
    /// <remarks>
    ///     Candidates are ranked by <see cref="ImageTextSource"/> (its declaration order is the
    ///     preference order), so a lower-ranked source never wins over a higher-ranked one that is
    ///     present. Empty or whitespace-only text is ignored, and an auto-generated object name is
    ///     ignored for the <see cref="ImageTextSource.PictureName"/> source, so a placeholder name
    ///     falls through to the next candidate rather than becoming a false description. Pure.
    /// </remarks>
    public static SelectedImageText? Select(IEnumerable<ImageTextCandidate> candidates)
    {
        ArgumentNullException.ThrowIfNull(candidates);

        // Track the highest-ranked usable candidate seen so far; a lower source ordinal outranks a higher one
        SelectedImageText? best = null;
        foreach (var candidate in candidates)
        {
            // Empty text carries nothing to say about the image, so it never competes
            var text = candidate.Text?.Trim();
            if (string.IsNullOrEmpty(text))
            {
                continue;
            }

            // An auto-generated object name is a placeholder, not a description; skip it and let a
            // weaker but honest source (a heading or the media name) be chosen instead
            if (candidate.Source == ImageTextSource.PictureName && IsAutoGeneratedName(text))
            {
                continue;
            }

            // Keep the candidate only when it outranks the best so far (or is the first usable one)
            if (best is null || candidate.Source < best.Source)
            {
                best = new SelectedImageText(text, candidate.Source, ConfidenceFor(candidate.Source));
            }
        }

        return best;
    }

    /// <summary>
    ///     Reports whether an object name is an auto-generated placeholder rather than a description.
    /// </summary>
    /// <param name="name">The candidate object name, or <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the name is empty or a generic auto-generated name; otherwise <see langword="false"/>.</returns>
    /// <remarks>
    ///     Matches an empty name and a generic base name followed by an optional number (for example
    ///     <c>Picture 1</c>, <c>Image 80</c>, or a bare <c>Diagram</c>), which is exactly what a tool
    ///     assigns when an author never named the drawing. A meaningful name that merely ends in a
    ///     number (for example <c>Blueprint 2</c>) is not matched, because its base is not a generic
    ///     placeholder. Pure and culture-independent.
    /// </remarks>
    public static bool IsAutoGeneratedName(string? name)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            return true;
        }

        // Reduce to a stable comparison form: whitespace collapsed to single spaces and lowercased
        var normalized = CollapseWhitespace(name).ToLowerInvariant();

        // Strip a trailing number (and the space before it) so "picture 1" reduces to "picture"
        var end = normalized.Length;
        while (end > 0 && char.IsDigit(normalized[end - 1]))
        {
            end--;
        }

        var core = normalized[..end].TrimEnd();
        return AutoGeneratedNames.Contains(core);
    }

    /// <summary>
    ///     Maps a candidate source to its stable camelCase provenance name.
    /// </summary>
    /// <param name="source">The source to name.</param>
    /// <returns>The camelCase provenance string (for example <c>description</c> or <c>pictureName</c>).</returns>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when <paramref name="source"/> is not a known source.</exception>
    /// <remarks>
    ///     Backends record this string in the manifest as the description's provenance, so a reader
    ///     can tell an authored description apart from a caption or a heading. Kept beside the policy
    ///     so every format names a source the same way. Pure.
    /// </remarks>
    public static string SourceName(ImageTextSource source) => source switch
    {
        ImageTextSource.Description => "description",
        ImageTextSource.Title => "title",
        ImageTextSource.Caption => "caption",
        ImageTextSource.PictureName => "pictureName",
        ImageTextSource.Heading => "heading",
        ImageTextSource.Uri => "uri",
        _ => throw new ArgumentOutOfRangeException(nameof(source), source, "Unknown image text source.")
    };

    /// <summary>
    ///     Maps a candidate source to the confidence tier that governs where its text may be used.
    /// </summary>
    /// <param name="source">The source the chosen text came from.</param>
    /// <returns>The confidence tier for the source.</returns>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when <paramref name="source"/> is not a known source.</exception>
    /// <remarks>
    ///     Authored text (description, title, caption) and a meaningful object name are descriptive;
    ///     a nearby heading is only contextual; the media name is a bare fallback. Throwing on an
    ///     unknown source keeps the mapping total, so a new source cannot silently default to the
    ///     wrong tier. Pure.
    /// </remarks>
    private static ImageTextConfidence ConfidenceFor(ImageTextSource source) => source switch
    {
        ImageTextSource.Description or ImageTextSource.Title
            or ImageTextSource.Caption or ImageTextSource.PictureName => ImageTextConfidence.Descriptive,
        ImageTextSource.Heading => ImageTextConfidence.Contextual,
        ImageTextSource.Uri => ImageTextConfidence.Fallback,
        _ => throw new ArgumentOutOfRangeException(nameof(source), source, "Unknown image text source.")
    };

    /// <summary>
    ///     Collapses every run of whitespace in a value into a single space and trims the ends.
    /// </summary>
    /// <param name="value">The value to normalize.</param>
    /// <returns>The value with internal whitespace runs reduced to one space.</returns>
    /// <remarks>Keeps the auto-generated-name comparison insensitive to odd spacing. Pure.</remarks>
    private static string CollapseWhitespace(string value)
    {
        var builder = new StringBuilder(value.Length);
        var lastWasSpace = false;
        foreach (var ch in value)
        {
            if (char.IsWhiteSpace(ch))
            {
                if (!lastWasSpace)
                {
                    builder.Append(' ');
                    lastWasSpace = true;
                }
            }
            else
            {
                builder.Append(ch);
                lastWasSpace = false;
            }
        }

        return builder.ToString().Trim();
    }
}

/// <summary>
///     How confidently a selected piece of image text actually describes the picture, which governs
///     where the text may honestly be used.
/// </summary>
/// <remarks>
///     <para>
///         The selection policy answers two different questions with one ranking: which candidate is
///         best, and how far that best candidate may be trusted. Confidence captures the second. It
///         is the mechanism that keeps a merely <em>contextual</em> hint (a nearby heading) or a
///         bare <em>fallback</em> (a media file name) from masquerading as an authored description.
///     </para>
///     <para>
///         Consumers gate on this: a filename slug may use any non-empty selection, but markdown
///         alt text is emitted only for a <see cref="Descriptive"/> selection so a heading is never
///         presented as if it described the image. The manifest records the selection and its source
///         for descriptive and contextual tiers alike, so provenance is preserved honestly without
///         inventing a description.
///     </para>
/// </remarks>
public enum ImageTextConfidence
{
    /// <summary>Text authored to describe the picture (description, title, caption, or a meaningful object name).</summary>
    /// <remarks>Safe to assert as the image's alt text because it was written about the image itself.</remarks>
    Descriptive,

    /// <summary>Text that locates the picture in the document but does not describe it (a nearby heading).</summary>
    /// <remarks>Usable as a naming hint and recorded in the manifest with its source, but never asserted as alt text.</remarks>
    Contextual,

    /// <summary>A last-resort identifier with no descriptive value (the media part name).</summary>
    /// <remarks>Keeps naming deterministic; carries no description, so it never becomes alt text or a manifest description.</remarks>
    Fallback
}

/// <summary>
///     Where a piece of candidate text describing an image came from, in decreasing order of how
///     directly it describes the picture.
/// </summary>
/// <remarks>
///     <para>
///         A backend gathers whatever text a document offers about an image — an author's alt-text
///         description, a caption, an embedded object name, a nearby heading — and the shared policy
///         (<see cref="ImageTextSelector"/>) ranks the candidates by this source so the most
///         directly descriptive one wins. The enumeration order <em>is</em> the preference order, so
///         a lower member never loses to a higher one when both are present.
///     </para>
///     <para>
///         Modeling the origin as a closed vocabulary keeps the choice auditable: the manifest can
///         record not just the chosen text but exactly where it came from, so a reader can tell an
///         authored description apart from a filename or a heading rather than trusting an opaque
///         string. Each format backend maps its own structures onto these members; the ranking and
///         the honesty rules live in one place regardless of format.
///     </para>
/// </remarks>
public enum ImageTextSource
{
    /// <summary>The author's alt-text description (for example <c>wp:docPr/@descr</c> in Word).</summary>
    /// <remarks>The most direct description a document can carry: text written specifically to describe the picture.</remarks>
    Description,

    /// <summary>The author's title for the drawing (for example <c>wp:docPr/@title</c> in Word).</summary>
    /// <remarks>Authored specifically for the picture, though a title is typically terser than a description.</remarks>
    Title,

    /// <summary>The text of an adjacent caption (for example a <c>Caption</c>-styled paragraph in Word).</summary>
    /// <remarks>Written to describe the figure, including any sequence numbering read structurally from the caption's fields.</remarks>
    Caption,

    /// <summary>An embedded object name (for example <c>pic:cNvPr/@name</c> in Word), often the original file name.</summary>
    /// <remarks>Frequently a meaningful file name, but discarded when it is an auto-generated placeholder such as <c>Picture 1</c>.</remarks>
    PictureName,

    /// <summary>The nearest preceding heading in the document body.</summary>
    /// <remarks>
    ///     Context, not a description: a heading names the section the picture sits under, which is a
    ///     useful naming hint but must never be asserted as the picture's alt text — a heading such
    ///     as <c>References</c> would imply a description of the image that does not exist.
    /// </remarks>
    Heading,

    /// <summary>The media part's own name within the package (the last resort).</summary>
    /// <remarks>A stable fallback that carries no description; used only to keep file naming deterministic when nothing better exists.</remarks>
    Uri
}

/// <summary>
///     One candidate piece of text describing an image, paired with where it came from.
/// </summary>
/// <param name="Text">
///     The candidate text, or <see langword="null"/> when the document offered nothing for this
///     source. Empty or whitespace-only text is treated the same as <see langword="null"/> by the
///     selector.
/// </param>
/// <param name="Source">The origin of the candidate, which determines its ranking and confidence.</param>
/// <remarks>
///     A backend produces one of these per source it can consult (an author description, a caption,
///     an object name, a heading, the media name) and hands the set to
///     <see cref="ImageTextSelector.Select"/>. Carrying the source alongside the text is what lets
///     the policy rank candidates and lets the manifest record provenance rather than an anonymous
///     string. Immutable and thread-safe.
/// </remarks>
public sealed record ImageTextCandidate(string? Text, ImageTextSource Source);

/// <summary>
///     The text a backend chose to describe an image, with its origin and how far it may be trusted.
/// </summary>
/// <param name="Text">The chosen, trimmed text. Never null or empty.</param>
/// <param name="Source">The origin the chosen text came from.</param>
/// <param name="Confidence">How confidently the text describes the image, which gates where it may be used.</param>
/// <remarks>
///     The result of <see cref="ImageTextSelector.Select"/>. A backend uses <see cref="Text"/> as a
///     naming hint regardless of confidence, but asserts it as alt text only when
///     <see cref="Confidence"/> is <see cref="ImageTextConfidence.Descriptive"/>; the manifest
///     records <see cref="Text"/> and <see cref="Source"/> for descriptive and contextual tiers so
///     provenance is preserved without inventing a description. Immutable and thread-safe.
/// </remarks>
public sealed record SelectedImageText(string Text, ImageTextSource Source, ImageTextConfidence Confidence);
