using System.Diagnostics;

namespace DemaConsulting.DocDown.TestSupport;

/// <summary>
///     Packs a project with <c>dotnet pack</c> and locates the produced <c>.nupkg</c>, isolating
///     each invocation so concurrent packs of the same project cannot collide.
/// </summary>
/// <remarks>
///     <para>
///         Packaging tests inspect the real artifact a release would publish, so they shell out to
///         the SDK rather than approximating a package by hand. The suite runs every test assembly
///         once per target framework (<c>net8.0</c>, <c>net9.0</c>, <c>net10.0</c>) in separate OS
///         processes, so the same packaging test packs the same project three times concurrently.
///         The pack target writes an intermediate <c>obj/Release/&lt;id&gt;.nuspec</c>; two packs of
///         one project share that path and one fails with "the process cannot access the file … it
///         is being used by another process." Because the collision is <em>across processes</em>, no
///         in-process lock or xUnit collection can order it.
///     </para>
///     <para>
///         The load-bearing fix is a per-invocation intermediate path: each call redirects the
///         generated nuspec to its own unique directory via <c>-p:NuspecOutputPath</c>, so no two
///         concurrent packs of the same project ever touch the same nuspec. Redirecting only the
///         nuspec (rather than the whole <c>BaseIntermediateOutputPath</c>) targets exactly the
///         racing file without flowing a global intermediate path into referenced projects — which
///         would pull the already-populated default <c>obj</c> back into the compilation and break
///         the build. Stateless and safe to call from many threads at once.
///     </para>
///     <para>
///         ApiMark introduces a second shared file with exactly the same shape. Its MSBuild target
///         runs after <c>Build</c> and writes the generated API reference to
///         <c>$(MSBuildProjectDirectory)\api</c>, one path per project, so two concurrent packs of
///         one project race on <c>api/api.md</c> and one fails with the same "used by another
///         process" error. Each call therefore also passes <c>-p:ApiMarkOutputRoot</c> pointing at
///         its own unique directory; each packable project composes
///         <c>$(ApiMarkOutputRoot)\$(MSBuildProjectName)\api</c> from it, so the isolation survives
///         the property flowing into referenced projects and a dependency's API reference cannot
///         leak into the packed project's <c>api/</c> folder. The package still receives a genuine
///         <c>api/</c> folder — the pack hook collects whatever <c>ApiMarkOutputDir</c> resolves to
///         — and the redirection has the further benefit that a packaging assertion reflects
///         documentation generated by that pack rather than whatever was left in the source tree.
///     </para>
/// </remarks>
public static class NuGetPackHelper
{
    /// <summary>
    ///     Packs a project to a folder and returns the absolute path of the produced package.
    /// </summary>
    /// <param name="projectPath">The absolute path to the <c>.csproj</c> to pack. Must not be null or empty.</param>
    /// <param name="packagePrefix">
    ///     The package id prefix used to locate the produced file (for example
    ///     <c>DemaConsulting.DocDown.Pdf</c>). Must not be null or empty.
    /// </param>
    /// <param name="outputFolder">
    ///     A writable folder to pack into; the caller owns its lifetime. Must not be null or empty.
    /// </param>
    /// <returns>The absolute path of the produced <c>.nupkg</c>.</returns>
    /// <exception cref="ArgumentException">Thrown when any argument is null or empty.</exception>
    /// <exception cref="InvalidOperationException">Thrown when the pack fails or produces no package.</exception>
    /// <remarks>
    ///     Invokes the SDK's <c>dotnet pack</c> so the assertion inspects the same artifact a release
    ///     would publish. Slow but faithful. The generated nuspec and the ApiMark output folder are
    ///     each redirected to a unique directory under <paramref name="outputFolder"/> for the
    ///     duration of the pack so concurrent packs of the same project cannot collide on the shared
    ///     <c>obj/Release</c> nuspec or the shared project-directory <c>api</c> folder; both
    ///     directories are removed on a best-effort basis before returning. Side effects: spawns a
    ///     process and writes the package plus transient build artifacts under
    ///     <paramref name="outputFolder"/>.
    /// </remarks>
    public static string PackAndLocateNupkg(string projectPath, string packagePrefix, string outputFolder)
    {
        // Reject malformed inputs at the call site so a failed pack cannot be mistaken for a defect
        ArgumentException.ThrowIfNullOrEmpty(projectPath);
        ArgumentException.ThrowIfNullOrEmpty(packagePrefix);
        ArgumentException.ThrowIfNullOrEmpty(outputFolder);

        // Give this pack its own nuspec directory so no two concurrent packs of the same project
        // share obj/Release/<id>.nuspec; the trailing separator is required by the pack target
        var nuspecDir = Path.Combine(outputFolder, "nuspec-" + Guid.NewGuid().ToString("N"))
            + Path.DirectorySeparatorChar;
        Directory.CreateDirectory(nuspecDir);

        // Give this pack its own ApiMark output root for the same reason: the default output is the
        // project directory's shared 'api' folder, which concurrent packs would write at once
        var apiDir = Path.Combine(outputFolder, "apimark-" + Guid.NewGuid().ToString("N"));

        try
        {
            RunPack(projectPath, outputFolder, nuspecDir, apiDir);

            // The package id prefix plus a version wildcard locates the single produced file
            var nupkg = Directory.GetFiles(outputFolder, packagePrefix + ".*.nupkg").FirstOrDefault();
            return nupkg ?? throw new InvalidOperationException(
                $"No .nupkg matching '{packagePrefix}.*.nupkg' was produced in '{outputFolder}'.");
        }
        finally
        {
            // Best-effort cleanup: the redirected nuspec and API reference are build intermediates,
            // not evidence — the evidence is the package itself
            TryDeleteDirectory(nuspecDir);
            TryDeleteDirectory(apiDir);
        }
    }

    /// <summary>
    ///     Runs <c>dotnet pack</c> for a project, redirecting the nuspec to a caller-chosen directory.
    /// </summary>
    /// <param name="projectPath">The absolute path to the project to pack.</param>
    /// <param name="outputFolder">The folder the package is written to.</param>
    /// <param name="nuspecDir">The unique directory the generated nuspec is redirected to.</param>
    /// <param name="apiDir">The unique root ApiMark's generated API reference is redirected under.</param>
    /// <exception cref="InvalidOperationException">Thrown when the process cannot start or exits non-zero.</exception>
    /// <remarks>
    ///     Captures both standard streams so a failure surfaces the SDK's own diagnostics rather than
    ///     an opaque exit code. Side effect: spawns and waits on a <c>dotnet</c> process.
    /// </remarks>
    private static void RunPack(string projectPath, string outputFolder, string nuspecDir, string apiDir)
    {
        // Invoke the .NET SDK from PATH deliberately: a build/test helper runs where the SDK is
        // provisioned, so resolving 'dotnet' via PATH is the intended, environment-agnostic contract
        // (there is no untrusted-PATH surface in a test helper). This matches how the packaging tests
        // have always invoked the SDK.
#pragma warning disable S4036 // Searching OS commands in PATH is security-sensitive
        var info = new ProcessStartInfo("dotnet")
#pragma warning restore S4036
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            WorkingDirectory = Path.GetDirectoryName(projectPath)
        };
        foreach (var argument in new[]
                 {
                     "pack", projectPath, "-c", "Release", "--nologo",
                     "-o", outputFolder, $"-p:NuspecOutputPath={nuspecDir}",
                     $"-p:ApiMarkOutputRoot={apiDir}"
                 })
        {
            info.ArgumentList.Add(argument);
        }

        using var process = Process.Start(info)
            ?? throw new InvalidOperationException("Could not start 'dotnet pack'.");
        var output = process.StandardOutput.ReadToEnd() + process.StandardError.ReadToEnd();
        process.WaitForExit();
        if (process.ExitCode != 0)
        {
            throw new InvalidOperationException($"'dotnet pack' failed:\n{output}");
        }
    }

    /// <summary>
    ///     Deletes a directory recursively, swallowing failures.
    /// </summary>
    /// <param name="directory">The directory to remove.</param>
    /// <remarks>
    ///     A transient lock on a build intermediate must never fail a test during teardown, so a
    ///     cleanup error is ignored. Best-effort I/O.
    /// </remarks>
    private static void TryDeleteDirectory(string directory)
    {
        try
        {
            if (Directory.Exists(directory))
            {
                Directory.Delete(directory, recursive: true);
            }
        }
        catch (IOException)
        {
            // Best-effort cleanup: a transient lock must not fail the test
        }
        catch (UnauthorizedAccessException)
        {
            // Best-effort cleanup: a read-only or in-use file must not fail the test
        }
    }
}
